### ISSUE TITLE
Am I missing something to build?

### ISSUE THREAD

**Issue by taromae** [mjesteve/Royale-ECharts#1] opened 2020-09-11 07:43 UTC
Hello mjesteve

I am very interested in this project of you.
I also think this work is very wonderful.

Unfortunately I haven't been able to reproduce this project well
  When building with VS code, the following error appears

**asconfig.json'" terminated with exit code: 5.**

Full error

MXMLJSC
+royalelib=c:\MoonshineSDKs\Royale_SDK\apache-royale-0.9.8-bin-js\royale-asjs\frameworks
--debug=true
+configname=royale
--targets=JSRoyale
--html-template=src/main/resources/royale-echarts-examples-template.html
--source-path+=src/main/royale
--source-path+=../royale-echarts/src/main/royale/
--namespace+=library://ns.apache.org/royale/echarts,../royale-echarts/src/main/resources/echarts-manifest.xml
--library-path+=${royalelib}/js/libs/MXRoyale-0.9.8-SNAPSHOT-js.swc
--js-library-path+=${royalelib}/js/libs/MXRoyale-0.9.8-SNAPSHOT-js.swc
--define+=BUILD::buildNumber,'buildNumber'
--define+=BUILD::buildVersion,'project.version'
--source-map=true
--
src/main/royale/App.mxml
command line 繧ｨ繝ｩ繝ｼ : 'c:\MoonshineSDKs\Royale_SDK\apache-royale-0.9.8-bin-js\royale-asjs\frameworks\js\libs\MXRoyale-0.9.8-SNAPSHOT-js.swc' 繧帝幕縺上％縺ｨ縺後〒縺阪∪縺帙ｓ縲・

command line 繧ｨ繝ｩ繝ｼ : 'c:\MoonshineSDKs\Royale_SDK\apache-royale-0.9.8-bin-js\royale-asjs\frameworks\js\libs\MXRoyale-0.9.8-SNAPSHOT-js.swc' 繧帝幕縺上％縺ｨ縺後〒縺阪∪縺帙ｓ縲・

0.7706018 seconds
The terminal process "C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe '-jar', 'c:\Users\y\.vscode\extensions\bowlerhatllc.vscode-nextgenas-1.2.2\bin\asconfigc.jar',
 '--sdk', 'c:\MoonshineSDKs\Royale_SDK\apache-royale-0.9.8-bin-js\royale-asjs', '--debug=true', '--project', 'c:\Users\y\Desktop\VSCodeWS\royale-echarts-examples\asconfig.json'"
  terminated with exit code: 5.

Terminal will be reused by tasks, press any key to close it.

0.7706018 seconds
The terminal process "C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe '-jar', 'c:\Users\y.maeda\.vscode\extensions\bowlerhatllc.vscode-nextgenas-1.2.2\bin\asconfigc.jar', '--sdk', 'c:\MoonshineSDKs\Royale_SDK\apache-royale-0.9.8-bin-js\royale-asjs', '--debug=true', '--project', 'c:\Users\y.maeda\Desktop\VSCodeWS\royale-echarts-examples\asconfig.json'" terminated with exit code: 5.

Terminal will be reused by tasks, press any key to close it.

Am I missing something?
The build environment is as follows
windows7
VSCode 1.48.0
Java version 1.8.0_172
ActionScript ^ MXML 1.2.2

I would appreciate it if you could give me a hint

Best regards
 
yushiro maeda

**Comment by mjesteve** [comment] 2020-09-11 08:45
Hello yushiro,
I am delighted that you like the project and I would very much like to receive your contributions. I'm just starting out but I really like ECharts and I hope I can get a useful wrapper.
I compile with maven, pom.xml, and I have no problems, can you try compiling like this?

In my case I use vsCode, I have never tried Moonshine.
In vsCode, I open a terminal window and put:
mvn clean install -DskipTests

You must first compile the library, royale-echarts, and then the example project.

Try and tell me your result.
If it doesn't work for you, we can ask at dev@royale.apache.org and see if they can help us (Piotr is one of the Moonshine developers)

I await your comments.

Hiedra.

**Comment by taromae** [comment] 2020-09-11 11:38
Hello mjesteve

Thank you for your reply

It's a big help

I don't seem to understand the composition well

First, I started compiling the library, but I got the following error

Downloaded from apache-plugins-release: https://repository.apache.org/content/repositories/releases/org/apache/maven/plugins/maven-deploy-plugin/3.0.0-M1/maven-deploy-plugin-3.0.0-M1.jar (34 kB at 25 kB/s)
[INFO]
[INFO] ------------------< com.proj.example:royale-echarts >-------------------
[INFO] Building Royale Lib Component ECharts 1.0-SNAPSHOT
[INFO] --------------------------------[ swc ]---------------------------------
[INFO]
[INFO] >>> maven-archetype-plugin:3.1.2:generate (default-cli) > generate-sources @ royale-echarts >>>
[INFO]
[INFO] --- royale-maven-plugin:0.9.8-SNAPSHOT:generate-extern (default-generate-extern) @ royale-echarts ---
[INFO]
[INFO] <<< maven-archetype-plugin:3.1.2:generate (default-cli) < generate-sources @ royale-echarts <<<
[INFO]
[INFO]
[INFO] --- maven-archetype-plugin:3.1.2:generate (default-cli) @ royale-echarts ---
[INFO] Generating project in Interactive mode
[INFO] Archetype repository not defined. Using the one from [org.apache.maven.archetypes:maven-archetype-quickstart:1.4] found in catalog remote
Define value for property 'groupId': com.proj.example
Define value for property 'artifactId': royale-echarts
Define value for property 'version' 1.0-SNAPSHOT: : 1.0-SNAPSHOT
Define value for property 'package' com.proj.example: : swc
Confirm properties configuration:
groupId: com.proj.example
artifactId: royale-echarts
version: 1.0-SNAPSHOT
package: swc
 Y: : Y
[INFO] ----------------------------------------------------------------------------
[INFO] Using following parameters for creating project from Archetype: maven-archetype-quickstart:1.4
[INFO] ----------------------------------------------------------------------------
[INFO] Parameter: groupId, Value: com.proj.example
[INFO] Parameter: artifactId, Value: royale-echarts
[INFO] Parameter: version, Value: 1.0-SNAPSHOT
[INFO] Parameter: package, Value: swc
[INFO] Parameter: packageInPathFormat, Value: swc
[INFO] Parameter: package, Value: swc
[INFO] Parameter: version, Value: 1.0-SNAPSHOT
[INFO] Parameter: groupId, Value: com.proj.example
[INFO] Parameter: artifactId, Value: royale-echarts
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  09:52 min
[INFO] Finished at: 2020-09-11T20:14:17+09:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.1.2:generate (default-cli) on project royale-echarts: Unable to add module to the current project as it is not of packaging type 'pom' -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException



I typed the following during the build, am I wrong?


Define value for property 'groupId': com.proj.example
Define value for property 'artifactId': royale-echarts
Define value for property 'version' 1.0-SNAPSHOT: : 1.0-SNAPSHOT
Define value for property 'package' com.proj.example: : swc



I used the Maven for JAVA plugin in VSCODE


This will first create a swc file, then put it in the royale-echarts-examples project and compile it again.

Is it correct?

so

mvn clean install -DskipTests

Is it okay to understand that this command is used in the royale-echarts-examples project?




Best regards


yushiro maeda

**Comment by ghost** [comment] 2020-09-16 06:04
Hello mjesteve

It's an interim report.

The royale-echarts project was successful


mvn clean install -P option-with-swf -DskipTests

The target folder has been created and the swc file has been created

Similarly, the royale-echarts-examples project was also carried out.

However, it seems that it is not possible to build because of the following error so far.


[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.proj.example:royale-echarts-examples:swf:1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.royale.compiler:royale-maven-plugin is missing. @ line 200, column 15
[WARNING] 'dependencies.dependency.scope' for org.apache.royale.framework:BasicTheme:swc:js must be one of [provided, compile, runtime, test, system] but is 'theme'. @ line 287, column 14
[WARNING] 'dependencies.dependency.scope' for org.apache.royale.framework:JewelTheme:swc:js must be one of [provided, compile, runtime, test, system] but is 'theme'. @ line 388, column 14
[WARNING] 'dependencies.dependency.scope' for org.apache.royale.framework:Jewel-Light-Flat-Primary-Sapphire-Theme:swc:js must be one of [provided, compile, runtime, test, system] but is 'theme'. @ line 397, column 14
[WARNING] 'dependencies.dependency.scope' for org.apache.royale.framework:Jewel-Light-Flat-Secondary-Blue-Theme:swc:js must be one of [provided, compile, runtime, test, system] but is 'theme'. @ line 405, column 14
[WARNING] 'dependencies.dependency.scope' for org.apache.royale.framework:Jewel-Light-Flat-Emphasized-Sunflower-Theme:swc:js must be one of [provided, compile, runtime, test, system] but is 'theme'. @ line 413, column 14
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] --------------< com.proj.example:royale-echarts-examples >--------------
[INFO] Building Royale Application 1.0-SNAPSHOT
[INFO] --------------------------------[ swf ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ royale-echarts-examples ---
[INFO] Deleting D:\Royale-ECharts-themes-loadLocal\royale-echarts-examples\target
[INFO]
[INFO] --- maven-resources-plugin:3.2.0:copy-resources (copy-resources-debug) @ royale-echarts-examples ---
[WARNING] File encoding has not been set, using platform encoding MS932. Build is platform dependent!
[WARNING] See https://maven.apache.org/general.html#encoding-warning
[WARNING] Using platform encoding (MS932 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Using 'null' encoding to copy filtered properties files.
[INFO] Copying 10 resources
[INFO] Copying 48 resources
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.597 s
[INFO] Finished at: 2020-09-16T14:37:44+09:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:3.2.0:copy-resources (copy-resources-debug) on project royale-echarts-examples: Input length = 1 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

I'll continue to work hard.

Best regards

yushiro maeda

**Comment by ghost** [comment] 2020-09-16 08:08
Hello mjesteve

Build Succeeded!

The cause was that my environment was a two-byte code.

For those who use it in other Asian countries

Add the following to pom.xml

**<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>**

In this project:   royale-echarts-examples 




＜properties＞
    ＜compiler.debug＞true＜/compiler.debug＞    
    ＜buildTimestamp＞DEV＜/buildTimestamp＞
    ＜royale.debug＞true</royale.debug＞
    ＜royale.framework.version＞0.9.8-SNAPSHOT＜/royale.framework.version＞
    ＜compiler.output-dir-debug＞${basedir}/target/javascript/bin/js-debug＜/compiler.output-dir-debug＞
    ＜compiler.output-dir-release＞${basedir}/target/javascript/bin/js-release＜/compiler.output-dir-release＞
    ＜project.build.sourceEncoding＞UTF-8＜/project.build.sourceEncoding＞
  ＜/properties＞


Unfortunately, vscode's asconfig.json doesn't work.


I had a hard time because I didn't know the basic things this time.

The following was helpful

https://github.com/apache/royale-asjs


Thank you very much for your support.
And I'm looking forward to the announcement at ApacheCon.

yushiro

**Comment by mjesteve** [comment] 2020-09-16 09:07
Hello yushiro,
I'm really sorry I didn't answer you before ... on the one hand I'm trying to set up a small example for ApacheCon with ECharts and "it consumes me all my time" and on the other hand "I have to study to be able to answer you" YOU KNOW MUCH MORE THAN ME !! ! hahahaha

I'm going to modify the pom, as you indicated, and when ApacheCon passes we could look in detail at the modification of the asconfig so that it compiles correctly, is that okay?

Thank you for your contributions, feel free to propose any improvement or modification, as I mentioned this project was born as an experiment and I hope we can do something really useful.

Thanks yushiro.
Hiedra

**Comment by ghost** [comment] 2020-09-29 06:21
Hello mjesteve

ApacheCon is just getting started!

I am looking forward to the presentation of this project from now on.

It's the most attention I've had in Royale's session.



After that, I noticed about three points, so I will continue to report

1_ Correct setting of UTF8
The following method seems to be good for the setting method.

<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
<project.reporting.outputencoding>UTF-8</project.reporting.outputencoding>

When I saw pam.xml in ASJS, it was set that way.
https://github.com/apache/royale-asjs/blob/develop/pom.xml

2_ About -P option-with-swf
There is no need. Build succeeds without this option

that is,　　 mvn clean install -dskiptests is correct

3_  royale-echarts-examples can be built even if royale-echarts are not built

I don't know why yet, but I see BUILD SUCCESS.

I'll try to investigate.



Now I imagine you're very busy getting ready.

Good luck with your presentation.

I am hoping that everything goes well.

yushiro

**Comment by mjesteve** [comment] 2020-09-29 07:49
Hi Yushiro,
I'm sorry to tell you that I'm not doing any introductions, but my colleagues Andrew and Chris are going to include some points in their Royale presentations.
I'm happy because "we've started something very interesting" right?
Yushiro, give me your email address and I'll add you to the git repo.

Are you going to attend the ECharts "ECharts: could the customization be both easy and highly personalized?" presentation?

**Comment by mjesteve** [comment] 2020-09-29 07:49
Hi Yushiro,
I'm sorry to tell you that I'm not doing any introductions, but my colleagues Andrew and Chris are going to include some points in their Royale presentations.
I'm happy because "we've started something very interesting" right?
Yushiro, give me your email address and I'll add you to the git repo.

Are you going to attend the ECharts "ECharts: could the customization be both easy and highly personalized?" presentation?

**Comment by ghost** [comment] 2020-09-29 09:11
Hello, mjesteve

Thank you for your reply.
I'm sorry I misunderstood you.
But I'm really looking forward to seeing this fascinating project announced.

If you know, let me know.
Which of the five presentations will be?
https://www.apachecon.com/acah2020/tracks/royale.html

I'm in Tokyo, so I'll see it in the middle of the night.
And thank you for letting me participate in this fascinating project.

I don't know what I can contribute, but I'll report it when I notice.
We will support this project from Japan.
I'll send you my e-mail address later.

Thank you very much.

Yushiro

**Comment by taromae** [comment] 2020-09-30 01:56
Hello, mjesteve

ECharts was introduced a little in yesterday's session.

I'm looking forward to the next session.

My email address is below

dockcafe@gmail.com

I will do my best so that I can contribute something

Yoshiro

**Comment by mjesteve** [comment] 2020-09-30 08:04
Hi,
I have invited you to the repo.
In the presentation that may come out some other example will be in Chris's presentation:
https://apachecon.com/acah2020/tracks/iot.html#W1655
Home automation with Apache - Christofer Dutz

Our presentation at the next ApacheCon, what do you think? 👍 

Hiedra

**Comment by taromae** [comment] 2020-09-30 13:03
Hello, Hiedra

It's very niceeeee !

Hiedra'Projects suggests a lot of possibilities
It will attract a lot of people, not just me

Io t's presentation, let's check it out

It ’s a luxury story,
I can't see two at the same time.....
I'm about to prepare for recording

Yoshiro

**Closed as completed** 2021-05-28 07:33 UTC
